//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect_Request
    {
        public int id { get; set; }
        public int res_id { get; set; }
        public string food_type { get; set; }
        public string collected_emp { get; set; }
        public string quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
