//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Collect_Request = new HashSet<Collect_Request>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int rid { get; set; }
    
        public virtual ICollection<Collect_Request> Collect_Request { get; set; }
        public virtual SignUp SignUp { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
