//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string provider_name { get; set; }
        public int rid { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SignUp SignUp { get; set; }
    }
}
